const DB={BMW:{"3 Series E90":{years:[2005,2006,2007,2008,2009,2010,2011,2012],engines:[["2.0 Diesel","N47D20","177 к.с.","Дизел"],["2.0 Petrol","N43B20","170 к.с.","Бензин"]]},"5 Series E60":{years:[2004,2005,2006,2007,2008,2009,2010],engines:[["2.0 Diesel","N47D20","—","Дизел"],["3.0 Diesel","—","—","Дизел"]]}}, "Mercedes-Benz":{"C-Class W204":{years:[2007,2008,2009,2010,2011,2012,2013,2014],engines:[["C220 CDI","—","—","Дизел"],["C200","—","—","Бензин"]]}},Audi:{"A4 B8":{years:[2008,2009,2010,2011,2012,2013,2014,2015],engines:[["2.0 TDI","—","—","Дизел"],["1.8 TFSI","—","—","Бензин"]]}},Volkswagen:{"Golf VI":{years:[2008,2009,2010,2011,2012],engines:[["1.6 TDI","—","—","Дизел"],["2.0 TDI","—","—","Дизел"],["1.4 TSI","—","—","Бензин"]]}}};
const OBD=[["P0301","Пропуск в запалването/горенето — цилиндър 1",["Запалителна система","Горивна система","Въздушен/вакуумен проблем","Механичен проблем"]],["P0171","Сместа е прекалено бедна — Bank 1",["Вакуумен теч","Недостатъчно гориво","Измерване на въздуха"]],["P0420","Ефективност на катализатора под праг",["Катализатор","Кислороден сензор","Изпускателен теч"]]];
let vehicle=JSON.parse(localStorage.getItem("vehicle")||"null"),repairs=JSON.parse(localStorage.getItem("repairs")||"[]");const $=x=>document.getElementById(x);
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");if(id=="specs")renderSpecs();if(id=="diagnostics")renderOBD();if(id=="repairs")renderRepairs()}
function init(){makeSelect.innerHTML=Object.keys(DB).map(x=>`<option>${x}</option>`).join("");makeSelect.onchange=renderModels;modelSelect.onchange=renderModel;renderModels();updateHome();renderOBD();renderRepairs()}
function renderModels(){modelSelect.innerHTML=Object.keys(DB[makeSelect.value]).map(x=>`<option>${x}</option>`).join("");renderModel()}
function renderModel(){let m=DB[makeSelect.value][modelSelect.value];yearSelect.innerHTML=m.years.map(x=>`<option>${x}</option>`).join("");engineSelect.innerHTML=m.engines.map((x,i)=>`<option value="${i}">${x[0]} • ${x[1]} • ${x[3]}</option>`).join("")}
function saveVehicle(){let m=makeSelect.value,o=modelSelect.value,y=yearSelect.value,e=DB[m][o].engines[+engineSelect.value];vehicle={make:m,model:o,year:y,engine:e};localStorage.setItem("vehicle",JSON.stringify(vehicle));updateHome();show("home")}
function updateHome(){selectedCar.textContent=vehicle?`${vehicle.make} ${vehicle.model} • ${vehicle.year}`:"Не е избран";selectedEngine.textContent=vehicle?`${vehicle.engine[0]} • ${vehicle.engine[1]} • ${vehicle.engine[3]}`:"Избери автомобил, за да започнеш."}
function renderSpecs(){if(!vehicle){vehicleSummary.innerHTML='<div class="item muted">Първо избери автомобил.</div>';specList.innerHTML="";return}vehicleSummary.innerHTML=`<div class="item"><b>${vehicle.make} ${vehicle.model}</b><span class="muted">${vehicle.year} • ${vehicle.engine[0]} • ${vehicle.engine[1]}</span></div>`;specList.innerHTML=["Моторно масло","Количество масло","Моменти на затягане","Сервизни интервали"].map(x=>`<div class="item"><b>${x}</b><span class="muted">Изисква проверен източник</span></div>`).join("")}
function renderOBD(){let q=(obdSearch.value||"").toUpperCase();obdList.innerHTML=OBD.filter(x=>x[0].includes(q)||x[1].toUpperCase().includes(q)).map(x=>`<button class="item" style="width:100%;color:#17181a" onclick="openOBD('${x[0]}')"><b>${x[0]}</b>${x[1]}</button>`).join("")}
function openOBD(c){let x=OBD.find(y=>y[0]==c);obdDetailBody.innerHTML=`<h2>${x[0]}</h2><div class="item"><b>Описание</b>${x[1]}</div><div class="item"><b>Възможни направления</b><ul>${x[2].map(y=>`<li>${y}</li>`).join("")}</ul></div><aside>OBD кодът е отправна точка за диагностика, а не автоматична диагноза.</aside>`;show("obdDetail")}
function addRepair(){let w=prompt("Какъв ремонт е извършен?");if(!w)return;repairs.unshift({date:new Date().toLocaleDateString("bg-BG"),work:w,vehicle:vehicle?vehicle.make+" "+vehicle.model:""});localStorage.setItem("repairs",JSON.stringify(repairs));renderRepairs()}
function renderRepairs(){repairList.innerHTML=repairs.length?repairs.map(r=>`<div class="item"><b>${r.work}</b><span class="muted">${r.vehicle||""} • ${r.date}</span></div>`).join(""):'<div class="item muted">Няма записи.</div>'}
function globalSearch(){let q=globalSearch.value.toLowerCase(),a=[];Object.entries(DB).forEach(([b,ms])=>Object.entries(ms).forEach(([m,d])=>d.engines.forEach(e=>a.push(`${b} ${m} ${e.join(" ")}`))));a=[...a,...OBD.map(x=>x.join(" "))].filter(x=>x.toLowerCase().includes(q));searchResults.innerHTML=a.map(x=>`<div class="item">${x}</div>`).join("")}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");init();